### ISSUE TITLE
Use more flags with zfs send

### ISSUE THREAD

**Issue by driesmp** [Jehops/zap#13] opened 2018-11-11 18:18 UTC
Hi @Jehops I like your tool so much, when local replication gets merged in master and I can get it through ports <3 love it. I was wondering if there is a possibility to use another send command.

Now we use this:
zfs send -p

Can we not use :
zfs send -Lcep

It doesn't hurt enabling them by default (from the ZFS manpage).
When one does not have the necessary features the extra flags will do nothing.

**Comment by Jehops** [comment] 2018-11-11 18:23
The `e` and `c` flags are on my TODO list to integrate, so that will happen soon.  I will also take a closer look at the `L` flag to see if it is safe to always use.

**Comment by Jehops** [comment] 2018-11-11 19:13
I pushed a new branch,  `local_plus_new_send_flags`, which is based off the `local_backups` branch.  I did some light testing, but could you also test to see if this gives you everything you are looking for and doesn't introduce any obvious, new issues?

**Comment by driesmp** [comment] 2018-11-11 20:13
I think I found a small issue. Destination is not quite correctly parsed? Might also be that I played to much with the tool ^^ that I just broke it without knowing why. Everything worked normal before I started getting this issue. I didn't observe any problems with the extra flags in the send command.

![image](https://user-images.githubusercontent.com/32487486/48317710-62f8fb00-e5f6-11e8-831c-63df12bb8e5d.png)

It sais "storage/zroot:storage/zroot"

EDIT: I also tried with "localhost:storage/zroot" in the zap:rep property but I get the same issue. Maybe I broke it 🥇 by playing to much. Unless its a real issue. I'll let you decide. Taking snapshots and trying again doesn't work either.

**Comment by driesmp** [comment] 2018-11-11 20:31
A watch-out for local replication, we should take care that "zap:snap=off" on the receiving storage dataset.
I had "zroot" replicating to storage/zroot and had "zap:snap=on" on "storage".
When I created "storage/zroot" it had "zap:snap=on (inherited which is fine)", this results in zap taking snapshots of the receiving location "storage/zroot". I don't think this is wanted behavior.
It was an easy fix by manually setting "zap:snap=off" on "storage/zroot" though. 

Maybe a warning or somthing in the manual page? 
"When replicating locally, it might be useful to turn off snapshots on the receiving dataset"

**Comment by Jehops** [comment] 2018-11-12 00:28
I pushed changes to the `local_plus_new_send_flags` branch to inherit the values for `zap:snap` and `zap:rep` (turn them off) on newly replicated datasets.

For your post with the screeshot, it looks like there is an issue extracting your hostname.  I added a new check to ensure the hostname is found.

**Comment by driesmp** [comment] 2018-11-12 17:52
Hi, the last change kind of conflicts when a hostname is not specified and only a dataset is specified for "zap:rep=receivingdataset". Also when zap:rep="localhost:receivingdataset" is specified; I can't get passed the check of hostname.

![image](https://user-images.githubusercontent.com/32487486/48365760-1c65d800-e6ac-11e8-8ef6-04e4da7f1692.png)
![image](https://user-images.githubusercontent.com/32487486/48365821-4919ef80-e6ac-11e8-9c48-87f954e6c60b.png)

**Comment by Jehops** [comment] 2018-11-12 18:45
The hostname is used a few different ways, so I think it would be best to unconditionally check that it was correctly extracted.  In other words, I think this is a case of the error check doing its job.

In your response above I see `zroot@ZAP__2018..`.  That should be `zroot@ZAP_<yourhostnamehere>_2018...` and I think that's why you are experiencing a problem.  So, even if a hostname is not specified, we should still do this check.

At the shell prompt that you are running `zap` from, could you report what the command `hostname -s` returns?

**Comment by driesmp** [comment] 2018-11-12 19:10
Hi, hostname was indeed empty 🥇 ... I'm testing this in a vm :) hostname error fixed after setting hostname.

Also, I think we will be forced to set "zap:snap=off" on the backup location eg; "storage/zroot" manually by the script if we are locally replicating. If we don't do this, and the back-up pool also takes snapshots with zap (eg: other datasets under it like storage/media, storage/downloads) then replication might fail from "zroot" to "storage/zroot" because there are already recent snapshots available (made on "storage/zroot" because "zap:snap=on" on "storage" and the property is inherited on "storage/zroot".

This can be fixed by setting and checking that back-up dataset location has "zap:snap=off" set.
The received streams should also inherit this property as they have been received under the backup location (the latter you already implemented, atleast if you inherit the property from the back-up dataset and not the root back-up dataset, so inherit it from storage/zroot (value of zap:rep="") and not storage).

To replicate the issue; 
replicate "zroot" to "storage/zroot" and have "zap:snap=on" on storage/zroot.

zap snap 1d [takes snapshots on zroot]
zap rep -vv [replicates like expected]
do some stuff on zroot
zap snap 1d [this takes snapshots on zroot AND storage/zroot/decendents]
zap rep -vv [this replication will tell you there is nothing to do]

**Comment by Jehops** [comment] 2018-11-13 02:40
Let me verify we are on the same page.  You are saying that inheriting `zap:snap` on the replicated dataset is insufficient, because a parent dataset on the receiving side might have `zap:snap=on`?  In your example, `zap:snap=on` for `storage/zroot`, which means `storage/zroot/descendents` will inherit `zap:snap=on` after the first full replication with `zap`. 

For this, a user must manually set `zap:snap=on` on the receiving side (`storage` or `storage/zroot` in your case).  But, I can't think of any major drawbacks to putting in a check.  It will probably just prevent confusion.

I pushed new changes to the `local_plus_new_send_flags` branch.  Does this do what you are looking for?

By the way, only `-v` is supported, not `-vv`.  I think the `-F` flag is related to this discussion as well.

**Comment by Jehops** [comment] 2018-11-13 02:46
I just re-read you past comment about `zap:snap` on the receiving dataset.  I think we are on the same page now, and the latest changes should hopefully prevent any of the pitfalls you described during the initial full replication when properties are received.

**Comment by driesmp** [comment] 2018-11-13 18:26
Ok let me test it, I think a line slipped in during your testing period. At line 317.

**Comment by driesmp** [comment] 2018-11-13 19:11
Yes, lovely @Jehops! I don't get the reproducable error anymore now that one has to set zap:snap to off on the receiving side. :) (and the receing pool has zap:snap=on the highest level of the pool) ^^. Would be lovely if you could push the updated tool in the ports tree.

I saw you commented line 324 & 325. They are indeed not necessary (default behavior of ZFS).

As a side note; have you ever considered integrating mbuffer support?

**Comment by Jehops** [comment] 2018-11-14 19:41
All three 'extra' lines were left over from testing. They will be gone in the commit I am about to push. I will update the docs soon too and if we don't encounter any new issues, I will merge these changes to the master branch and update the port. Thanks.

**Comment by Jehops** [comment] 2018-11-14 19:42
I will take a look at mbuffer.  I'm not too familiar with it.

**Comment by Jehops** [comment] 2018-11-14 19:56
Would you like to be referred to as `Duffyx` under contributors?

**Comment by driesmp** [comment] 2018-11-14 19:59
Thats nice of you :) you can use my name which I use in stuff related to FreeBSD; "Dries Michiels". Thanks!

**Comment by driesmp** [comment] 2018-11-14 21:00
Oh forgot to leave my e-mail, driesm.michiels@gmail.com , again thx for doing this!

**Comment by Jehops** [comment] 2018-11-14 22:55
Happy to do it.  Thanks for contributing.  I will close this issue and commit in a week.  Of course, if you notice other problems in the meantime, please let me know.

**Comment by driesmp** [comment] 2018-11-15 16:53
Hi, I did one more test run and I have noticed that after the first replication of my root dataset, it sets zap:snap back to on on the receiving dataset as seen in the picture. While I manually put it to off initially.
This is not wanted behavior. Is there something we can do about this?
![image](https://user-images.githubusercontent.com/32487486/48568250-4236eb00-e8ff-11e8-98f3-9f6e70025c6b.png)

After manually setting it back to off, and replicating again I get nested datasets. Each time I replicate, an extra layer of zroot comes on there. This is because zap:rep is also received and storage/zroot will replicate to storage/zroot. and then storage/zroot/zroot.. will replicate to storage/zroot etc. I feel like zap: properties should not be received when locally replicating.

![image](https://user-images.githubusercontent.com/32487486/48568524-e1f47900-e8ff-11e8-9931-c29295efcd03.png)

**Comment by Jehops** [comment] 2018-11-15 23:49
I can reproduce the problem.  This is tricky.  It would be ideal to preserve all these properties to create an identical backup that can be restored exactly as it was, but this is clearly a problem.  It's too bad there aren't replication flags to exclude preservation of some properties.  I will push a fix within the next few days.

**Comment by Jehops** [comment] 2018-11-16 00:19
I pushed another change that still sends the properties, but explicitly sets `zap:snap` and `zap:rep` to `off` on the target dataset when doing a full replication.  I only had time to do a quick test.  I will try to test again in a day or two when I am not so swamped.  If you have time to test, please let me know if this works for you.

**Comment by driesmp** [comment] 2018-11-16 17:11
Yea this is a tricky thing damn. I found that it works altough I often get that the bookmark of my root datapool is missing and cannot be replicated.

![image](https://user-images.githubusercontent.com/32487486/48636357-edf93d00-e9ca-11e8-8df6-639d3b44a9b4.png)
![image](https://user-images.githubusercontent.com/32487486/48636362-f18cc400-e9ca-11e8-8725-ad7357d50268.png)

As you can see in the pic, there is no bookmark of zroot#, and thus fails to replicate. I found that its only the case when replicating more than once, not at the first send (then its fine).

**Comment by Jehops** [comment] 2018-11-18 18:36
I am  not able to reproduce this.  The bookmark is only used as a fallback when a snapshot is missing, so a snapshot must be missing.  Could you produce a recipe to help me reproduce this?  

Side note: You probably want the `-F` flag when replicating.  I have gone back and forth trying to decide if that should be the default

```
% sudo zpool create -m none storage /torrent/file1
% sudo zfs create -o readonly=on storage/test1
% sudo zfs allow -u zap canmount,compression,create,mountpoint,mount,receive,refreservation,userprop,volmode storage/test1
% sudo zfs create zroot/test1
% sudo zfs allow -u zap bookmark,diff,hold,send,snapshot zroot
% sudo zfs allow -u zap bookmark,diff,hold,send,snapshot zroot/test1
% sudo zfs set zap:snap=on zroot zroot/test1
% sudo zfs set zap:rep=storage/test1 zroot
% sudo zfs set zap:rep=off zroot/ROOT/default zroot/tmp zroot/usr zroot/var

% sudo -u zap zap snap -v 1d
Sun 18 Nov 2018 14:18:18 AST
Creating snapshots...
zfs snap zroot@ZAP_bravo_2018-11-18T14:18:18-0400--1d
zfs snap zroot/ROOT@ZAP_bravo_2018-11-18T14:18:18-0400--1d
zfs snap zroot/test1@ZAP_bravo_2018-11-18T14:18:18-0400--1d

% sudo -u zap zap rep -v
Sun 18 Nov 2018 14:18:27 AST
Replicating...
No remote snapshots found. Sending full stream.
zfs send -Lcep zroot@ZAP_bravo_2018-11-18T14:18:18-0400--1d | zfs recv -Fu -v -d storage/test1
receiving full stream of zroot@ZAP_bravo_2018-11-18T14:18:18-0400--1d into storage/test1@ZAP_bravo_2018-11-18T14:18:18-0400--1d
cannot receive readonly property on storage/test1: permission denied
cannot receive atime property on storage/test1: permission denied
received 44.4KB stream in 1 seconds (44.4KB/sec)
zfs bookmark zroot@ZAP_bravo_2018-11-18T14:18:18-0400--1d zroot#ZAP_bravo_2018-11-18T14:18:18-0400--1d
Set canmount=noauto for storage/test1
Set zap:snap=off for storage/test1
Set zap:rep=off for storage/test1
No remote snapshots found. Sending full stream.
zfs send -Lcep zroot/ROOT@ZAP_bravo_2018-11-18T14:18:18-0400--1d | zfs recv -Fu -v -d storage/test1
receiving full stream of zroot/ROOT@ZAP_bravo_2018-11-18T14:18:18-0400--1d into storage/test1/ROOT@ZAP_bravo_2018-11-18T14:18:18-0400--1d
received 44.4KB stream in 1 seconds (44.4KB/sec)
zfs bookmark zroot/ROOT@ZAP_bravo_2018-11-18T14:18:18-0400--1d zroot/ROOT#ZAP_bravo_2018-11-18T14:18:18-0400--1d
Set canmount=noauto for storage/test1/ROOT
Set zap:snap=off for storage/test1/ROOT
Set zap:rep=off for storage/test1/ROOT
No remote snapshots found. Sending full stream.
zfs send -Lcep zroot/test1@ZAP_bravo_2018-11-18T14:18:18-0400--1d | zfs recv -Fu -v -d storage/test1
receiving full stream of zroot/test1@ZAP_bravo_2018-11-18T14:18:18-0400--1d into storage/test1/test1@ZAP_bravo_2018-11-18T14:18:18-0400--1d
received 44.7KB stream in 1 seconds (44.7KB/sec)
zfs bookmark zroot/test1@ZAP_bravo_2018-11-18T14:18:18-0400--1d zroot/test1#ZAP_bravo_2018-11-18T14:18:18-0400--1d
Set canmount=noauto for storage/test1/test1
Set zap:snap=off for storage/test1/test1
Set zap:rep=off for storage/test1/test1

% sudo zap snap -v 1d
Sun 18 Nov 2018 14:18:40 AST
Creating snapshots...
zfs snap zroot@ZAP_bravo_2018-11-18T14:18:40-0400--1d
zfs snap zroot/ROOT@ZAP_bravo_2018-11-18T14:18:40-0400--1d
zfs snap zroot/test1@ZAP_bravo_2018-11-18T14:18:40-0400--1d

% sudo -u zap zap rep -v
Sun 18 Nov 2018 14:18:45 AST
Replicating...
zfs send -Lce -I zroot@ZAP_bravo_2018-11-18T14:18:18-0400--1d zroot@ZAP_bravo_2018-11-18T14:18:40-0400--1d | zfs recv -du  -v storage/test1
receiving incremental stream of zroot@ZAP_bravo_2018-11-18T14:18:40-0400--1d into storage/test1@ZAP_bravo_2018-11-18T14:18:40-0400--1d
received 312B stream in 1 seconds (312B/sec)
zfs bookmark zroot@ZAP_bravo_2018-11-18T14:18:40-0400--1d zroot#ZAP_bravo_2018-11-18T14:18:40-0400--1d
Created bookmark for zroot@ZAP_bravo_2018-11-18T14:18:40-0400--1d.
zfs send -Lce -I zroot/ROOT@ZAP_bravo_2018-11-18T14:18:18-0400--1d zroot/ROOT@ZAP_bravo_2018-11-18T14:18:40-0400--1d | zfs recv -du  -v storage/test1
receiving incremental stream of zroot/ROOT@ZAP_bravo_2018-11-18T14:18:40-0400--1d into storage/test1/ROOT@ZAP_bravo_2018-11-18T14:18:40-0400--1d
received 312B stream in 1 seconds (312B/sec)
zfs bookmark zroot/ROOT@ZAP_bravo_2018-11-18T14:18:40-0400--1d zroot/ROOT#ZAP_bravo_2018-11-18T14:18:40-0400--1d
Created bookmark for zroot/ROOT@ZAP_bravo_2018-11-18T14:18:40-0400--1d.
zfs send -Lce -I zroot/test1@ZAP_bravo_2018-11-18T14:18:18-0400--1d zroot/test1@ZAP_bravo_2018-11-18T14:18:40-0400--1d | zfs recv -du  -v storage/test1
receiving incremental stream of zroot/test1@ZAP_bravo_2018-11-18T14:18:40-0400--1d into storage/test1/test1@ZAP_bravo_2018-11-18T14:18:40-0400--1d
received 312B stream in 1 seconds (312B/sec)
zfs bookmark zroot/test1@ZAP_bravo_2018-11-18T14:18:40-0400--1d zroot/test1#ZAP_bravo_2018-11-18T14:18:40-0400--1d
Created bookmark for zroot/test1@ZAP_bravo_2018-11-18T14:18:40-0400--1d.
```

**Comment by driesmp** [comment] 2018-11-18 19:04
I am not able to reproduce this anymore either ... which is good!
Probably some leftovers of previous playing. Sorry for the noise.

**Comment by Jehops** [comment] 2018-12-01 20:29
The latest version, 0.8, incorporates these changes.  The FreeBSD port/package will be updated soon.  Thanks again.

**Closed as completed by Jehops** 2018-12-01 20:29 UTC
